#!/bin/sh
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
#
# The contents of this file are subject to the Mozilla Public License Version
# 1.1 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
# The Original Code is generate_update_statistics.sh.
#
# The Initial Developer of the Original Code is
# Samuel Sidler.
# Portions created by the Initial Developer are Copyright (C) 2008
# the Initial Developer. All Rights Reserved.
#
# Contributor(s):
#   Samuel Sidler <samuel.sidler@gmail.com> (Original Author)
#   Smokey Ardisson <alqahira@ardisson.org>
#
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
#
# ***** END LICENSE BLOCK *****

if [ $# -ne 3 ]; then
  if [ $# -ne 2 ]; then
    echo "Usage: $0 <date in DD/Mmm format> <caminobrowser.org-ssl_log path>"
    exit 1
  fi
fi

date="$1"
if [ $# -eq 2 ]; then
  file="$2"
else
  file="$2 $3"
fi
badips="204.234.28.|149.150.236.250|203.42.177.[16-19]|200.19.92.|189.108.14.138|72.10.105.23|205.202.243.[23-47]|63.245.210.43|204.234.25.253|97.119.20.170|97.119.24.98|149.150.236.189|75.135.19.219"

echo "$date"

grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep -c " /update-check?os="
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -c "x86"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -c "ppc"

echo "=================="
echo "By OS"
# Only run the greps once to generate the OS and Version/OS numbers, and then echo them in the appropriate locations to match the spreadsheet.
cm16_pan=`grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=10\.3" | grep -E -c "version=1\.6"`
cm16_tig=`grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=10\.4" | grep -E -c "version=1\.6"`
cm16_lep=`grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=10\.5" | grep -E -c "version=1\.6"`
cm16_snl=`grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=10\.6" | grep -E -c "version=1\.6"`
cm20_tig=`grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=10\.4" | grep -E -c "version=2\.0"`
cm20_lep=`grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=10\.5" | grep -E -c "version=2\.0"`
cm20_snl=`grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=10\.6" | grep -E -c "version=2\.0"`
cm21_tig=`grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=10\.4" | grep -E -c "version=2\.1"`
cm21_lep=`grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=10\.5" | grep -E -c "version=2\.1"`
cm21_snl=`grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=10\.6" | grep -E -c "version=2\.1"`
# Do math to derive the OS numbers across all versions; this saves us 3 formulas/day in the spreadsheet.
echo $cm16_pan
echo `expr $cm16_tig "+" $cm20_tig "+" $cm21_tig`
echo `expr $cm16_lep "+" $cm20_lep "+" $cm21_lep`
echo `expr $cm16_snl "+" $cm20_snl "+" $cm21_snl`

echo "=================="
echo "By Version"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.11(I|\&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.10(I|\&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.9(I|\&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.8(I|\&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.7(I|\&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.6(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.5(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.4(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.3(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.2(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6\.1(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "1\.6(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0\.7(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0\.6(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0\.5(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0\.4(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0\.3(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0\.2(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0\.1(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0b4(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0b3(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0b2(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0b1(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.0a1(I|&)"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep -E -c "2\.1a1(I|&)"

echo "=================="
echo "By Version and OS"
echo $cm16_pan
echo $cm16_tig
echo $cm16_lep
echo $cm16_snl
echo $cm20_tig
echo $cm20_lep
echo $cm20_snl
echo $cm21_tig
echo $cm21_lep
echo $cm21_snl

# echo "=================="
# echo "1.6 l10n"
# grep "$date" $file | grep -Ev "$badips" | grep " /update-check?os=" | grep "version=1\.6" | grep "lang=" | cut -d " " -f 7 | cut -d "&" -f 5 | sort | uniq -c

echo "=================="
echo "2.0 l10n"
grep "$date" $file | grep -Ev "$badips" | grep "Sparkle/" | grep " /update-check?os=" | grep "version=2\.0" | grep "lang=" | cut -d " " -f 7 | cut -d "&" -f 5 | sort | uniq -c
